-- Criações de TABELAS

CREATE TABLE PequenoVarejo
(
    id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome     VARCHAR2(255) NOT NULL,
    CNPJ     VARCHAR2(18) NOT NULL UNIQUE,
    cidade VARCHAR2(100) NOT NULL,
    estado VARCHAR2(50) NOT NULL
    Endereco VARCHAR2(500)
);

CREATE TABLE Venda
(
    id                 NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_varejo          NUMBER(10) NOT NULL,
    nome_produto       VARCHAR2(255) NOT NULL,
    tamanho_embalagem  NUMBER(10,2),
    preco_produto      NUMBER(10,2),
    unidade_de_medida  VARCHAR2(50),
    quantidade         NUMBER(10,3),
    data_hora          TIMESTAMP WITH TIME ZONE
                       DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,

    CONSTRAINT fk_venda_varejo
        FOREIGN KEY (id_varejo)
        REFERENCES PequenoVarejo (id)
        ON DELETE CASCADE
);

