-- ==========================================
-- 🔹 RECRIAÇÃO COMPLETA DAS TABELAS
-- ==========================================

-- ⚠️ Apaga se já existirem
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE venda CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE pequenoVarejo CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ==========================================
-- 🔸 Criação da tabela principal (PequenoVarejo)
-- ==========================================
CREATE TABLE pequenoVarejo
(
    id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome      VARCHAR2(255) NOT NULL,
    cnpj      VARCHAR2(18) NOT NULL UNIQUE,
    endereco  VARCHAR2(500),
    cidade    VARCHAR2(100) NOT NULL,
    estado    VARCHAR2(50) NOT NULL,
    cep       VARCHAR2(10) NOT NULL
);

-- ==========================================
-- 🔸 Criação da tabela Venda
-- ==========================================
CREATE TABLE venda
(
    id                 NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_varejo          NUMBER(10) NOT NULL,
    nome_produto       VARCHAR2(255) NOT NULL,
    tamanho_embalagem  NUMBER(10,2),
    preco_unitario      NUMBER(10,2),
    unidade_de_medida  VARCHAR2(50),
    quantidade         NUMBER(10,3),
    data_hora          TIMESTAMP WITH TIME ZONE
                       DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP) NOT NULL,

    CONSTRAINT fk_venda_varejo
        FOREIGN KEY (id_varejo)
        REFERENCES pequenoVarejo (id)
        ON DELETE CASCADE
);
