-- ==========================================
-- 🔹 SCRIPT DE LIMPEZA GERAL DE DADOS
-- ==========================================

SET SERVEROUTPUT ON;

BEGIN
    -- 1️⃣ Apagar todos os registros na ordem correta
    DELETE FROM venda;
    DELETE FROM pequenoVarejo;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('✔️ Todos os registros foram removidos.');

    -- 2️⃣ Resetar IDENTITY da tabela VENDA
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE venda MODIFY id DROP IDENTITY';
        EXECUTE IMMEDIATE 'ALTER TABLE venda MODIFY id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
        DBMS_OUTPUT.PUT_LINE('✅ Identity da tabela VENDA resetado para iniciar em 1.');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ Erro ao resetar identity de VENDA: ' || SQLERRM);
    END;

    -- 3️⃣ Resetar IDENTITY da tabela PEQUENOVAREJO
    BEGIN
        EXECUTE IMMEDIATE 'ALTER TABLE pequenoVarejo MODIFY id DROP IDENTITY';
        EXECUTE IMMEDIATE 'ALTER TABLE pequenoVarejo MODIFY id NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1)';
        DBMS_OUTPUT.PUT_LINE('✅ Identity da tabela PEQUENOVAREJO resetado para iniciar em 1.');
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('⚠️ Erro ao resetar identity de PEQUENOVAREJO: ' || SQLERRM);
    END;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('🎯 Limpeza e reset concluídos com sucesso.');
END;
/
